export * from './ministries';
export * from './ministry-detail/ministry-detail.page';
export * from './ministry-detail/keys/keys.page';
export * from './ministry-detail/members/members.page';
export * from './ministry-detail/scales/scales.page';
export * from './ministry-detail/songs/songs.page';
export * from './member-detail/member-detail.page';
export * from './scale-detail/scale-detail.page';
export * from './song-detail/song-detail.page';
