export const SONGS = [
  {
    "songID": 1,
    "title": "Grande é o Senhor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 1,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 2,
    "title": "Ele é Exaltado",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 1,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 3,
    "title": "Tu és bom",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 2,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 4,
    "title": "Deixa queimar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 3,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 5,
    "title": "O carpinteiro",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 3,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 6,
    "title": "Esconda-me em ti",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 3,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 7,
    "title": "Aleluia (Quem Muito Foi Perdoado)\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 3,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 8,
    "title": "Maranata, Ora Vem",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 3,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 9,
    "title": "Quero conhecer Jesus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 3,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 10,
    "title": "Casa de Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 11,
    "title": "Consagração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 12,
    "title": "Corpo e Família",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 13,
    "title": "Entrega",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 14,
    "title": "Rendido Estou",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 15,
    "title": "Somos Livres",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 16,
    "title": "Sonda-me",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 17,
    "title": "Vitoria No Deserto",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 4,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 18,
    "title": "Raridade",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 5,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 19,
    "title": "Quando ele vem aqui",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 6,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 20,
    "title": "Eu e Minha Casa",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 21,
    "title": "Milagres",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 22,
    "title": "Muralhas",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 23,
    "title": "Eu vou Vencer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 24,
    "title": "Não tenho medo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 25,
    "title": "País da Adoração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 26,
    "title": "Pela Fé\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 27,
    "title": "Pra sempre teu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 28,
    "title": "Vou crer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 7,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 29,
    "title": "Sua Presença é real",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 8,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 30,
    "title": "Enche Este Lugar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 8,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 31,
    "title": "Deus Incrível",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 32,
    "title": "Jump",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 33,
    "title": "Me Ajoelho Pra Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 34,
    "title": "Nada a temer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 35,
    "title": "Não poderia ser melhor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 36,
    "title": "O Impossível não Existe",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 37,
    "title": "Invencível",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 38,
    "title": "Segunda Chance",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 39,
    "title": "Dono do meu barco",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 40,
    "title": "Tu és",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 41,
    "title": "Ide",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 9,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 42,
    "title": "O Espírito de Deus está aqui",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 10,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 43,
    "title": "Tu és o rei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 11,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 44,
    "title": "Rei dos Reis",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 12,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 45,
    "title": "Espírito Santo, Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 13,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 46,
    "title": "Eu te amo Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 13,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 47,
    "title": "Incomparável",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 13,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 48,
    "title": "Que Direito",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 13,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 49,
    "title": "Aguas que saram",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 14,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 50,
    "title": "Entra no meu lar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 14,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 51,
    "title": "Faz o meu milagre",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 14,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 52,
    "title": "Mar da galileia",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 14,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 53,
    "title": "Providencia",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 14,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 54,
    "title": "Rompendo Limites",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 14,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 55,
    "title": "Eu me rendo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 15,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 56,
    "title": "Como na primeira vez",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 16,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 57,
    "title": "A casa é sua",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 17,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 58,
    "title": "Era eu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 17,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 59,
    "title": "Faz arder",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 17,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 60,
    "title": "Yeshua",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 17,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 61,
    "title": "Com Muito Louvor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 18,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 62,
    "title": "Hino da Vitória",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 18,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 63,
    "title": "Aquele que esta feliz",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 19,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 64,
    "title": "Vamos celebrar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 19,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 65,
    "title": "Debaixo do meu pé\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 20,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 66,
    "title": "Eu te buscarei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 21,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 67,
    "title": "Não há outro como tu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 21,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 68,
    "title": "Teu reino",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 21,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 69,
    "title": "Vida de Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 21,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 70,
    "title": "Até  que eu não consiga mais ficar de pé\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 22,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 71,
    "title": "Deus de Abraão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 23,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 72,
    "title": "Sempre Foi Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 23,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 73,
    "title": "Aviva-nos / A terra clama",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 24,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 74,
    "title": "Céus e terra se encontram",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 24,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 75,
    "title": "Cultura do Céu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 24,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 76,
    "title": "Abra os olhos do meu coração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 77,
    "title": "Agnus Dei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 78,
    "title": "Aguas Profundas",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 79,
    "title": "Correndo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 80,
    "title": " D'ele, por ele, para ele\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 81,
    "title": "Ele vem (Incendeia Senhor a sua Noiva)\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 82,
    "title": "Essência da Adoração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 83,
    "title": "Eu sou Livre",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 84,
    "title": "Filho de Davi",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 85,
    "title": "Poderoso Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 86,
    "title": "Quero ser como criança",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 87,
    "title": "Tudo que tem Fôlego",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 25,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 88,
    "title": "Que ele cresça",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 26,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 89,
    "title": "Deus é Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 27,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 90,
    "title": "Vim falar com Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 27,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 91,
    "title": "Aclame ao Senhor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 28,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 92,
    "title": "Canção do Apocalipse",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 28,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 93,
    "title": "Me ama",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 28,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 94,
    "title": "Preciso de ti",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 28,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 95,
    "title": "Te agradeço",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 28,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 96,
    "title": "Favor de Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 29,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 97,
    "title": "La vou eu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 29,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 98,
    "title": "Ouvir o teu falar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 29,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 99,
    "title": "Pedra na mão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 29,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 100,
    "title": "Se eu me humilhar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 29,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 101,
    "title": "Som da Liberdade",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 30,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 102,
    "title": "Aonde está Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 31,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 103,
    "title": "Colheita",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 31,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 104,
    "title": "Me ajude a melhorar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 31,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 105,
    "title": "Os anjos te louvam",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 31,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 106,
    "title": "Se eu cair",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 31,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 107,
    "title": "Tudo que eu sou",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 31,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 108,
    "title": "Sou casa",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 32,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 109,
    "title": "Posso clamar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 33,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 110,
    "title": "Espírito Santo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 34,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 111,
    "title": "Eu vejo a gloria",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 34,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 112,
    "title": "A Alegria do Senhor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 113,
    "title": "Adestra",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 114,
    "title": "Agindo Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 115,
    "title": "Ainda que a figueira",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 116,
    "title": "Batiza-me",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 117,
    "title": "Caia Fogo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 118,
    "title": "Chorem",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 119,
    "title": "Deus não está morto",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 120,
    "title": "Dançar na chuva",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 121,
    "title": "Emanuel",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 122,
    "title": "Eu fui comprado",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 123,
    "title": "Eu vou abrir o meu coração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 124,
    "title": "Eu jamais serei o mesmo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 125,
    "title": "Eu vou subir a montanha",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 126,
    "title": "Faz chover",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 127,
    "title": "Fogo consumidor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 128,
    "title": "Galileu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 129,
    "title": "Grandes Coisas",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 130,
    "title": "Infinitamente mais",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 131,
    "title": "Já estou crucificado",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 132,
    "title": "Há Um rio",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 133,
    "title": "O Hino",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 134,
    "title": "Jesus Filho de Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 135,
    "title": "Luz do mundo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 136,
    "title": "Mil Cairão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 137,
    "title": "Nada Além do Sangue",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 138,
    "title": "Não mais escravos",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 139,
    "title": "Pai de Multidões",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 140,
    "title": "Se Não for Pra te Adorar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 141,
    "title": "Sede de Justiça",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 142,
    "title": "Seu sangue",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 143,
    "title": "Uma Nova História",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 144,
    "title": "Yeshua",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 35,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 145,
    "title": "Canção de Jó\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 146,
    "title": "Criador",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 147,
    "title": "Eu quero mais",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 148,
    "title": "Tremenda graça",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 149,
    "title": "Meu coração é teu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 150,
    "title": "Meu Salvador",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 151,
    "title": "Tu És bom",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 36,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 152,
    "title": "Na Terra Como No Ceu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 37,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 153,
    "title": "Aqui vou eu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 154,
    "title": "Celebrarei tua gloria",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 155,
    "title": "Deixar Brilhar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 156,
    "title": "Eu amo meu jesus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 157,
    "title": "Me esbaldar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 158,
    "title": "O filho do homem",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 159,
    "title": "Pra onde irei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 160,
    "title": "Vai chover",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 161,
    "title": "Eu vou viver pra ti",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 162,
    "title": "Vem comigo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 38,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 163,
    "title": "A Bênção",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 39,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 164,
    "title": "Minha Bênção",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 39,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 165,
    "title": "Vitorioso Ès",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 39,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 166,
    "title": "Deus Proverá\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 40,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 167,
    "title": "Aleluia",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 168,
    "title": "Atos 2",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 169,
    "title": "Creio que tu és a cura",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 170,
    "title": "Desperta",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 171,
    "title": "Diz",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 172,
    "title": "Eu navegarei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 173,
    "title": "Lugar Secreto",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 174,
    "title": "Hosana",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 175,
    "title": "Pra onde iremos",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 176,
    "title": "Me aproximou",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 177,
    "title": "Jesus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 178,
    "title": "Teu santo nome",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 41,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 179,
    "title": "Nosso Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 42,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 180,
    "title": "Conversão (Foi na cruz)\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 43,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 181,
    "title": "Grandioso es tu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 43,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 182,
    "title": "Porque ele vive",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 43,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 183,
    "title": "Celebrai a Cristo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 43,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 184,
    "title": "Ha um lugar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 44,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 185,
    "title": "Jesus é o caminho",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 44,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 186,
    "title": "Vem andar Comigo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 44,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 187,
    "title": "Yeshua",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 44,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 188,
    "title": "Minha morada",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 45,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 189,
    "title": "Toca em mim de Novo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 45,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 190,
    "title": "Ousado amor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 46,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 191,
    "title": "Enche-me",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 46,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 192,
    "title": "Canção ao Cordeiro",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 47,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 193,
    "title": "No meio dos louvores",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 47,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 194,
    "title": "Alivio",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 195,
    "title": "Vem me buscar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 49,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 196,
    "title": "Nada Mais Satisfaz",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 197,
    "title": "Amar como você\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 53,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 198,
    "title": "Encontrei o Meu Lugar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 199,
    "title": "Furioso Oceano",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 200,
    "title": "Se Até os Anjos se Prostram",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 201,
    "title": "So quero Queimar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 202,
    "title": "Louco por você\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 50,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 203,
    "title": "Beija-me com tua glória",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 54,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 204,
    "title": "Terra Seca",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 54,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 205,
    "title": "Algo novo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 55,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 206,
    "title": "Cartas de Amor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 55,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 207,
    "title": "Oh quão lindo esse nome é\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 55,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 208,
    "title": "Aos pés da cruz",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 209,
    "title": "Comunhão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 210,
    "title": "Vou seguir com fé\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 211,
    "title": "Jeová e o teu Cavaleiro",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 212,
    "title": "Meu alvo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 213,
    "title": "Nova Criatura",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 214,
    "title": "Te agradeço",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 215,
    "title": "Vou deixar na cruz",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 216,
    "title": "Abba",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 217,
    "title": "Closer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 218,
    "title": "Em teus braços",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 219,
    "title": "Liberdade",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 220,
    "title": "Santo Espírito",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 221,
    "title": "Só quero ver você\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 222,
    "title": "Ele vive",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 58,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 223,
    "title": "Eu me rendo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 58,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 224,
    "title": "Getsêmani",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 58,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 225,
    "title": "Espero por ti",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 226,
    "title": "Eu vou construir",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 227,
    "title": "Lindo és",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 228,
    "title": "Mais forte que a morte",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 229,
    "title": "Milagres",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 230,
    "title": "Por que ele vive, Amem",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 231,
    "title": "Santo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 232,
    "title": "Vai valer a pena",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 59,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 233,
    "title": "Fogo Em Teus Olhos",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 60,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 234,
    "title": "Eu tenho você\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 61,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 235,
    "title": "Ate que ele venha",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 62,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 236,
    "title": "Estamos de pé\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 62,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 237,
    "title": "Vem, Senhor Jesus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 62,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 238,
    "title": "Agora é festa",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 63,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 239,
    "title": "Hosana",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 63,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 240,
    "title": "Vai brilhar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 63,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 241,
    "title": "Alfa e Ômega",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 64,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 242,
    "title": "Não Morrerei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 65,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 243,
    "title": "Ele não desiste de você\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 65,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 244,
    "title": "A Casa Eu Arrumei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 66,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 245,
    "title": "Tua Presença Vale Mais",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 66,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 246,
    "title": "Jó\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 67,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 247,
    "title": "Nâo pare",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 67,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 248,
    "title": "Olharei para o alto",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 67,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 249,
    "title": "Maranata",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 68,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 250,
    "title": "Pra sempre",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 68,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 251,
    "title": "Maravilhosa Graça",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 70,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 252,
    "title": "Novo Tempo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 70,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 253,
    "title": "Ressuscita",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 70,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 254,
    "title": "Última Chance",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 70,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 255,
    "title": "Ao único",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 256,
    "title": "Em Espírito e em verdade",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 257,
    "title": "Maravilhoso e",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 258,
    "title": "Jesus cristo eu te amo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 56,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 259,
    "title": "Dia e noite",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 260,
    "title": "É tudo sobre você\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 261,
    "title": "Emaus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 262,
    "title": "Isaias 6",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 263,
    "title": "Meus votos",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 264,
    "title": "Oh! se fendesses",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 265,
    "title": "Para que entre o rei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 266,
    "title": "Só tu es santo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 267,
    "title": "Pra onde eu irei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 268,
    "title": "Uma coisa",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 71,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 269,
    "title": "Fogo que consome",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 72,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 270,
    "title": "Majestade Santa",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 72,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 271,
    "title": "Quando a luz se apagar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 272,
    "title": " Aquieta minh'alma\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 57,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 273,
    "title": "Aumenta o fogo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 274,
    "title": "Em tua Presença",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 275,
    "title": "Filho do Deus vivo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 276,
    "title": "Gloria e Honra",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 277,
    "title": "Não seremos abalados",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 278,
    "title": "Nenhum Deus como Tu",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 279,
    "title": "O senhor é bom",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 280,
    "title": "Que se abram os céus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 281,
    "title": "Rei do meu coração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 282,
    "title": "Teu amor não falha",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 74,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 283,
    "title": "Deus esta aqui",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 75,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 284,
    "title": "Poder",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 75,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 285,
    "title": "Minha obsessão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 76,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 286,
    "title": "Eu vou",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 287,
    "title": "Ele continua sendo bom",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 288,
    "title": "Jardim da inocência",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 289,
    "title": "Seja Engrandecido",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 290,
    "title": "Mais que uma voz",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 291,
    "title": "Viver em comunhão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 292,
    "title": "Oh Gloria",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 77,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 293,
    "title": "Tua Presença",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 78,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 294,
    "title": "Livre sou",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 79,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 295,
    "title": "Não temerei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 79,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 296,
    "title": "Eu te agradeço",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 80,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 297,
    "title": "Ninguém explica Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 80,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 298,
    "title": "Pra te adorar eu vivo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 81,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 299,
    "title": "Diante de Ti",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 300,
    "title": "Espírito Enche a minha Vida",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 301,
    "title": "Um chamado",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 302,
    "title": "Eu celebrarei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 303,
    "title": "Foi por amor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 304,
    "title": "Jesus em tua presença",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 305,
    "title": "Nada é Impossível",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 306,
    "title": "Não Temerei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 307,
    "title": "Um Chamado",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 308,
    "title": "Vim Para Adorar-te",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 82,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 309,
    "title": "Jesus meu guia é\t ",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 83,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 310,
    "title": "Faz um milagre em mim",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 84,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 311,
    "title": "Mil graus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 85,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 312,
    "title": "Plano perfeito",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 85,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 313,
    "title": "Romance",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 86,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 314,
    "title": "Isaias 9",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 87,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 315,
    "title": "Eu te louvarei Meu bom Jesus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 88,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 316,
    "title": "Meu coração te pertence",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 89,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 317,
    "title": "Minha Fonte",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 89,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 318,
    "title": "Somos Um",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 89,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 319,
    "title": "Tudo é Novo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 89,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 320,
    "title": "Quão grande é o meu Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 90,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 321,
    "title": "Cadeias Quebra",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 90,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 322,
    "title": "Caminho no Deserto",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 90,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 323,
    "title": "Ruja o leão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 91,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 324,
    "title": "Isaias 9",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 92,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 325,
    "title": "Teu amor não falha",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 92,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 326,
    "title": "Arde Outra Vez",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 327,
    "title": "Casa do Pai",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 328,
    "title": "Cheios do Espírito Santo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 329,
    "title": "Dá-me Um coração segundo o seu coração",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 330,
    "title": "Deus da Força",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 331,
    "title": "Deus da minha vida",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 332,
    "title": "Deus me ama",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 333,
    "title": "Eu escolho Deus",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 334,
    "title": "Nada além de ti",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 335,
    "title": "Oh, Meu Irmãozinho",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 93,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 336,
    "title": "Eu Só Quero Tua Presença",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 94,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 337,
    "title": "Um milhão de anos",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 94,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 338,
    "title": "A alegria do senhor",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "https://www.youtube.com/watch?v=Mahr1CaNpo4",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 94,
    "keyID": 34,
    "ministryID": 1
  },
  {
    "songID": 339,
    "title": "Pode Morar Aqui",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 94,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 340,
    "title": "Abro mão",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 341,
    "title": "Deus de Promessas",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 342,
    "title": "Deus do Impossível",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 343,
    "title": "Eu vou viver uma virada",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 344,
    "title": "Marca da Promessa",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 345,
    "title": "Na Corte do Egito",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 346,
    "title": "Não recuarei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 347,
    "title": "O Chão vai tremer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 348,
    "title": "Olha pra mim",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 349,
    "title": "Restitui",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 350,
    "title": "Sobre as Aguas",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 351,
    "title": "Te conhecer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 352,
    "title": "Te louvarei",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 353,
    "title": "Toda sorte de bênçãos",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 354,
    "title": "Tua graça me basta",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 95,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 355,
    "title": "Me derramar",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 96,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 356,
    "title": "Quebrantado",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 96,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 357,
    "title": "Reina em mim",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 96,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 358,
    "title": "Senhor te quero",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 96,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 359,
    "title": "Maranata/ Lágrimas de Fogo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 97,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 360,
    "title": "Sou um milagre",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 98,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 361,
    "title": "Como prometeste",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 99,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 362,
    "title": "O que a tua gloria fez comigo",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 99,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 363,
    "title": "O que meu Deus Vai fazer",
    "tags": [],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "",
    "lyricUrl": "",
    "chordsUrl": "",
    "artistID": 100,
    "keyID": 1,
    "ministryID": 1
  },
  {
    "songID": 364,
    "title": "Sai da Frente",
    "tags": [
      "Júbilo"
    ],
    "observations": "",
    "audioUrl": "",
    "youtubeUrl": "https://www.youtube.com/watch?v=4J5He0w_KfE",
    "lyricUrl": "",
    "chordsUrl": "https://www.cifraclub.com.br/arena-louvor/sai-da-frente/",
    "artistID": 9,
    "keyID": 16,
    "ministryID": 1
  }
]