import { SongKey } from '@prisma/client';

export const SONG_KEYS: SongKey[] = [
  { songKeyID: 1, notation: 'C', name: 'Do Maior' },
  { songKeyID: 2, notation: 'Cm', name: 'Do Menor' },
  { songKeyID: 3, notation: 'C#', name: 'Do Sustenido Maior' },
  { songKeyID: 4, notation: 'C#m', name: 'Do Sustenido Menor' },
  { songKeyID: 5, notation: 'Db', name: 'Re Bemol Maior' },
  { songKeyID: 6, notation: 'Dbm', name: 'Re Bemol Menor' },
  { songKeyID: 7, notation: 'D', name: 'Re Maior' },
  { songKeyID: 8, notation: 'Dm', name: 'Re Menor' },
  { songKeyID: 9, notation: 'D#', name: 'Re Sustenido Maior' },
  { songKeyID: 10, notation: 'D#m', name: 'Re Sustenido Menor' },
  { songKeyID: 11, notation: 'Eb', name: 'Mi Bemol Maior' },
  { songKeyID: 12, notation: 'Ebm', name: 'Mi Bemol Menor' },
  { songKeyID: 13, notation: 'E', name: 'Mi Maior' },
  { songKeyID: 14, notation: 'Em', name: 'Mi Menor' },
  { songKeyID: 15, notation: 'F', name: 'Fa Maior' },
  { songKeyID: 16, notation: 'Fm', name: 'Fa Menor' },
  { songKeyID: 17, notation: 'F#', name: 'Fa Sustenido Maior' },
  { songKeyID: 18, notation: 'F#m', name: 'Fa Sustenido Menor' },
  { songKeyID: 19, notation: 'Gb', name: 'Sol Bemol Maior' },
  { songKeyID: 20, notation: 'Gbm', name: 'Sol Bemol Menor' },
  { songKeyID: 21, notation: 'G', name: 'Sol Maior' },
  { songKeyID: 22, notation: 'Gm', name: 'Sol Menor' },
  { songKeyID: 23, notation: 'G#', name: 'Sol Sustenido Maior' },
  { songKeyID: 24, notation: 'G#m', name: 'Sol Sustenido Menor' },
  { songKeyID: 25, notation: 'Ab', name: 'La Bemol Maior' },
  { songKeyID: 26, notation: 'Abm', name: 'La Bemol Menor' },
  { songKeyID: 27, notation: 'A', name: 'La Maior' },
  { songKeyID: 28, notation: 'Am', name: 'La Menor' },
  { songKeyID: 29, notation: 'A#', name: 'La Sustenido Maior' },
  { songKeyID: 30, notation: 'A#m', name: 'La Sustenido Menor' },
  { songKeyID: 31, notation: 'Bb', name: 'Si Bemol Maior' },
  { songKeyID: 32, notation: 'Bbm', name: 'Si Bemol Menor' },
  { songKeyID: 33, notation: 'B', name: 'Si Maior' },
  { songKeyID: 34, notation: 'Bm', name: 'Si Menor' },
];
